### ISSUE TITLE
Is this still up to date for Big Sur and Monterey?

### ISSUE THREAD

**Issue by 5T33Z0** [corpnewt/CsrDecode#2]
Is this still up to date to decode the csr-active-config values for Big Sur and Monterey?

Because if I enable all the values I get `0x7ff`, hex-swapped `FF070000` which was used in macOS Catalina to disable SIP)

But in Big Sur 0x867 or `67080000` hex-swapped is used instead.

So I am wondering if there have been new entries added to that list. If so, can you update the tool?

Thanks.

**Comment by corpnewt** [comment]
I haven't kept this script updated - I ended up expanding the functionality to include a number of other common bitmasks and writing another script called [BitmaskDecode](https://github.com/corpnewt/BitmaskDecode).  That's updated for Big Sur, but I haven't looked into Monterey settings yet (it's still in beta, and I doubt any of the source for the csr values is available yet).

-CorpNewt

**Comment by 5T33Z0** [comment]
Thanks. I didn't even know this Tool existed!
